locals {
  resource_types = {
    key_vault                   = "Microsoft.KeyVault/vaults"
    app_service                 = "Microsoft.Web/sites"
    sql_server                  = "Microsoft.Sql/servers"
    sql_database                = "Microsoft.Sql/servers/databases"
    storage_account             = "Microsoft.Storage/storageAccounts"
    network_security_group      = "Microsoft.Network/networkSecurityGroups"
    app_service_plan            = "Microsoft.Web/serverfarms"
    virtual_network             = "Microsoft.Network/virtualNetworks"
    virtual_machine             = "Microsoft.Compute/virtualMachines"
    network_interface           = "Microsoft.Network/networkInterfaces"
    public_ip                   = "Microsoft.Network/publicIPAddresses"
    automation_account          = "Microsoft.Automation/AutomationAccounts"
    application_gateway         = "Microsoft.Network/applicationGateways"
    data_factory                = "Microsoft.DataFactory/factories"
    load_balancer               = "Microsoft.Network/loadBalancers"
    ddos                        = "Microsoft.Network/ddosProtectionPlans"
    virtual_network_gateway     = "Microsoft.Network/virtualNetworkGateways"
    azure_firwall               = "Microsoft.Network/azureFirewalls"
    relay_namespace             = "Microsoft.Relay/namespaces"
    traffic_manager             = "Microsoft.Network/trafficManagerProfiles"
    event_hub                   = "Microsoft.EventHub/namespaces"
    notification_hub            = "Microsoft.NotificationHubs/namespaces"
    dns_zone                    = "Microsoft.Network/dnszones"
    frontdoor                   = "Microsoft.Network/frontdoors"
    elastic_pool                = "Microsoft.Sql/servers/elasticpools"
    recovery_services_vault     = "Microsoft.RecoveryServices/vaults"
    log_analytics_workspace     = "Microsoft.OperationalInsights/workspaces"
    machine_leaning_workspace   = "Microsoft.MachineLearningServices/workspaces"
    kubernetes_containerservice = "Microsoft.ContainerService/managedClusters"
    container_registry          = "Microsoft.ContainerRegistry/registries"
    application_insights        = "Microsoft.Insights/components"
  }
}
